### PR TITLE
fixes #160 - addresses error deserializing malformed json string

### LINKED ISSUE #160: JSON deserializing empty string, leads to nil error
**The problematic code:** https://github.com/DmitryTsepelev/store_model/blob/9a502a3fcee1dfeb31be12a0a20c416dc1afc8d4/lib/store_model/types/one.rb#L66-L67

**The issue:**
* When attempting to decode an incorrectly formatted String (i.e. '\7a1bb3}3b2b'), the existing `rescue` logic assigns a `nil` value to a `payload` variable that is then operated on as if it were a Hash
* This can lead to the below error:
```ruby
gems/store_model-2.1.1/lib/store_model/types/one.rb:93:in `block in deserialize_by_types': undefined method `key?' for nil:NilClass (NoMethodError)
```

**Proposed Solution:**
* We should return nil (i.e. in the case of line 71) instead of allowing the above NoMethodError to happen

I'm happy to cut a PR for this once the issue is acknowledged and proposed solution agreed upon

### PR DESCRIPTION
**Pull request by agiveygives**
fixes #160

### CODE REVIEW

File: lib/store_model/types/one.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@ def serialize(value)
       def deserialize(value)
         case value
         when String
-          payload = ActiveSupport::JSON.decode(value) rescue nil
+          payload = ActiveSupport::JSON.decode(value) rescue {}
```
Comment (jcdennen) [inline lib/store_model/types/one.rb:66]: good call assigning an empty Hash

**Review by jcdennen — APPROVED** [review]

**Review by DmitryTsepelev — APPROVED** [review]
Makes sense! Thank you for fixing that @agiveygives and thank you @jcdennen for the report 🙂
